export const BOAT_REGISTER_REQUEST = 'BOAT_REGISTER_REQUEST';
export const BOAT_REGISTER_SUCCESS = 'BOAT_REGISTER_SUCCESS';
export const BOAT_REGISTER_FAILURE = 'BOAT_REGISTER_FAILURE';

export const GET_BOAT_DETAILS_REQUEST = 'GET_BOAT_DETAILS_REQUEST';
export const GET_BOAT_DETAILS_SUCCESS = 'GET_BOAT_DETAILS_SUCCESS';
export const GET_BOAT_DETAILS_FAILURE = 'GET_BOAT_DETAILS_FAILURE';

export const GET_ALL_BOAT_DETAILS_REQUEST = 'GET_ALL_BOAT_DETAILS_REQUEST';
export const GET_ALL_BOAT_DETAILS_SUCCESS = 'GET_ALL_BOAT_DETAILS_SUCCESS';
export const GET_ALL_BOAT_DETAILS_FAILURE = 'GET_ALL_BOAT_DETAILS_FAILURE';

export const EDIT_BOAT_LISTING_REQUEST = 'EDIT_BOAT_LISTING_REQUEST';
export const EDIT_BOAT_LISTING_SUCCESS = 'EDIT_BOAT_LISTING_SUCCESS';
export const EDIT_BOAT_LISTING_FAILURE = 'EDIT_BOAT_LISTING_FAILURE';

export const DELETE_BOAT_LISTING_REQUEST = 'DELETE_BOAT_LISTING_REQUEST';
export const DELETE_BOAT_LISTING_SUCCESS = 'DELETE_BOAT_LISTING_SUCCESS';
export const DELETE_BOAT_LISTING_FAILURE = 'DELETE_BOAT_LISTING_FAILURE';

export const ADD_BOAT_IMAGES_REQUEST = 'ADD_BOAT_IMAGES_REQUEST';
export const ADD_BOAT_IMAGES_SUCCESS = 'ADD_BOAT_IMAGES_SUCCESS';
export const ADD_BOAT_IMAGES_FAILURE = 'ADD_BOAT_IMAGES_FAILURE';

export const DELETE_BOAT_IMAGES_REQUEST = 'DELETE_BOAT_IMAGES_REQUEST';
export const DELETE_BOAT_IMAGES_SUCCESS = 'DELETE_BOAT_IMAGES_SUCCESS';
export const DELETE_BOAT_IMAGES_FAILURE = 'DELETE_BOAT_IMAGES_FAILURE';