export const FETCH_USER_INFO_REQUEST = 'FETCH_USER_INFO_REQUEST';
export const FETCH_USER_INFO_SUCCESS = 'FETCH_USER_INFO_SUCCESS';
export const FETCH_USER_INFO_FAILURE = 'FETCH_USER_INFO_FAILURE';

export const UPDATE_USER_INFO_REQUEST = 'UPDATE_USER_INFO_REQUEST';
export const UPDATE_USER_INFO_SUCCESS = 'UPDATE_USER_INFO_SUCCESS';
export const UPDATE_USER_INFO_FAILURE = 'UPDATE_USER_INFO_FAILURE';

export const FETCH_PUBLIC_USER_INFO_REQUEST = 'FETCH_PUBLIC_USER_INFO_REQUEST';
export const FETCH_PUBLIC_USER_INFO_SUCCESS = 'FETCH_PUBLIC_USER_INFO_SUCCESS';
export const FETCH_PUBLIC_USER_INFO_FAILURE = 'FETCH_PUBLIC_USER_INFO_FAILURE';