export const FETCH_USER_INFO_REQUEST = 'FETCH_USER_INFO_REQUEST';
export const FETCH_USER_INFO_SUCCESS = 'FETCH_USER_INFO_SUCCESS';
export const FETCH_USER_INFO_FAILURE = 'FETCH_USER_INFO_FAILURE';

export const UPDATE_USER_INFO_REQUEST = 'UPDATE_USER_INFO_REQUEST';
export const UPDATE_USER_INFO_SUCCESS = 'UPDATE_USER_INFO_SUCCESS';
export const UPDATE_USER_INFO_FAILURE = 'UPDATE_USER_INFO_FAILURE';

export const FETCH_PUBLIC_USER_INFO_REQUEST = 'FETCH_PUBLIC_USER_INFO_REQUEST';
export const FETCH_PUBLIC_USER_INFO_SUCCESS = 'FETCH_PUBLIC_USER_INFO_SUCCESS';
export const FETCH_PUBLIC_USER_INFO_FAILURE = 'FETCH_PUBLIC_USER_INFO_FAILURE';

export const ADD_USER_PROFILE_PICTURE_REQUEST = 'ADD_USER_PROFILE_PICTURE_REQUEST';
export const ADD_USER_PROFILE_PICTURE_SUCCESS = 'ADD_USER_PROFILE_PICTURE_SUCCESS';
export const ADD_USER_PROFILE_PICTURE_FAILURE = 'ADD_USER_PROFILE_PICTURE_FAILURE';

export const DELETE_USER_PROFILE_PICTURE_REQUEST = 'DELETE_USER_PROFILE_PICTURE_REQUEST';
export const DELETE_USER_PROFILE_PICTURE_SUCCESS = 'DELETE_USER_PROFILE_PICTURE_SUCCESS';
export const DELETE_USER_PROFILE_PICTURE_FAILURE = 'DELETE_USER_PROFILE_PICTURE_FAILURE';